#!/bin/bash
set -e

WORKFLOW_ID=$1
WORKFLOW_VERSION=$2
if [ -n "$WORKFLOW_VERSION" ]; then
  ARGS="{\"workflowId\":\"$WORKFLOW_ID\", \"workflowVersion\": \"$WORKFLOW_VERSION\"}"
else
  ARGS="{\"workflowId\":\"$WORKFLOW_ID\"}"
fi

./exec.sh "get-workflow" "$ARGS"