#!/bin/bash
set -e

WORKFLOW_ID=$1
PAGE_NUMBER=$2

if [ -n "$PAGE_NUMBER" ]; then
  ARGS="{\"workflowId\":\"$WORKFLOW_ID\", \"pageNumber\":$PAGE_NUMBER}"
else
  ARGS="{\"workflowId\":\"$WORKFLOW_ID\"}"
fi

./exec.sh "get-workflow-history" "$ARGS"
