#!/bin/bash
set -e

npm run build

PAGE_NUMBER=$1

if [ -n "$PAGE_NUMBER" ]; then
  ARGS="{\"pageNumber\":$PAGE_NUMBER}"
else
  ARGS="{}"
fi

PAYLOAD="{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"tools/call\",\"params\":{\"name\":\"list-workflows\",\"arguments\":${ARGS}}}"

./exec.sh "$PAYLOAD"
