#!/bin/bash
set -e

WORKFLOW_ID=$1
SESSION_MODE=$2
PAGE_NUMBER=$3

# Build the arguments JSON
ARGS="{\"workflowId\":\"$WORKFLOW_ID\""
if [ -n "$SESSION_MODE" ]; then
  ARGS="$ARGS,\"sessionMode\":\"$SESSION_MODE\""
fi
if [ -n "$PAGE_NUMBER" ]; then
  ARGS="$ARGS,\"pageNumber\":$PAGE_NUMBER"
fi
ARGS="$ARGS}"

./exec.sh "list-sessions" "$ARGS"
