#!/bin/bash
set -e

WORKFLOW_ID=$1
COMPONENT_ID=$2
P_VALUES=$3
if [[ -z "${P_VALUES}" ]]; then
  ARGS="{\"workflowId\":\"$WORKFLOW_ID\", \"componentId\":\"$COMPONENT_ID\"}"
else
  ARGS="{\"workflowId\":\"$WORKFLOW_ID\", \"componentId\":\"$COMPONENT_ID\", \"placeholderValues\": ${P_VALUES}}"
fi

./exec.sh "run-workflow" "$ARGS"