// This file is auto-generated by @hey-api/openapi-ts

/**
 * Base command for workflow execution operations
 */
export type BaseWorkflowCommand = {
  /**
   * UUID identifier of the component to start running from
   */
  componentId: string;
  /**
   * Production or Test Mode
   */
  mode?: "PROD" | "TEST";
  /**
   * A object containing placeholder keys and values.
   * - Keys must be from the set of placeholders available to the specified component.
   * - All keys are optional at the API level, but omitting them may of course cause the workflow to fail.
   * - Values are validated against the placeholder type.
   * - datetime placeholders MUST be in ISO-8601 format, but may omit timezone, offset, or the whole time portion.
   * - list placeholders MUST EITHER be sent as a JSON List or a Bracketed String (see example).
   * - Values may not be sent as JSON objects, instead keys should use dotted form.
   */
  placeholderValues?: {
    [key: string]: {
      [key: string]: unknown;
    };
  };
};

/**
 * A command for starting a workflow
 */
export type RunWorkflowCommand = BaseWorkflowCommand & {
  /**
   * Optional project version to run. If not provided, uses latest version based on session mode.
   */
  projectVersion?: number;
  /**
   * Optional project session ID to copy placeholder values from.
   */
  projectSessionId?: string;
};

/**
 * A command for rerunning a workflow
 */
export type RerunWorkflowCommand = BaseWorkflowCommand & {
  /**
   * Required project version to run.
   */
  projectVersion: number;
  /**
   * Required project session ID to copy placeholder values from.
   */
  projectSessionId: string;
};

export type StandardWorkflow86Exception = {
  /**
   * HTTP Status code (matching the status of the response)
   */
  httpStatus?: number;
  /**
   * Error ID to be quoted in any potential support requests
   */
  errorId?: string;
  /**
   * Message containing details of the problem
   */
  message?: string;
};

/**
 * A response when starting a workflow
 */
export type RunWorkflowResponse = {
  /**
   * UUID identifier of the workflow started (echoed)
   */
  workflowId?: string;
  /**
   * UUID identifier of the component started (echoed)
   */
  componentId?: string;
  /**
   * Normalized values of the placeholders provided in the input
   */
  placeholderValues?: {
    [key: string]: string;
  };
  /**
   * UUID identifier of the session started
   */
  sessionId?: string;
  /**
   * URL to poll for session progress details
   */
  sessionUrl?: string;
};

export type PageOfWorkflowSummary = {
  /**
   * The page of response data as an array
   */
  _embedded: Array<WorkflowSummary>;
  /**
   * The zero-indexed page number of the response data
   */
  _pageNumber: number;
  /**
   * True iff this page is the final page
   */
  _lastPage: boolean;
  _links: {
    [key: string]: string;
  };
};

/**
 * The page of response data as an array
 */
export type WorkflowSummary = {
  /**
   * UUID id of this workflow
   */
  workflowId: string;
  /**
   * The name of this workflow
   */
  name: string;
  /**
   * The description of this workflow
   */
  description: string;
  /**
   * true if this workflow has been published, false if this workflow is still in draft
   */
  published: boolean;
  _links: {
    [key: string]: string;
  };
};

/**
 * The components that make up this workflow
 */
export type ComponentDetails = {
  /**
   * UUID id of the Component
   */
  componentId: string;
  /**
   * Type of the Component
   */
  type: string;
  /**
   * Name of the Component
   */
  name: string;
  /**
   * Description of the Component
   */
  description: string;
  /**
   * UUID IDs of the components that will be executed after this one
   */
  nextComponents: Array<string>;
  /**
   * Placeholders used as input by this component
   */
  placeholders: {
    [key: string]: string;
  };
};

export type WorkflowVersionSummary = {
  /**
   * UUID id of this workflow
   */
  workflowId: string;
  /**
   * The integer version of this workflow
   */
  version: number;
  /**
   * The lifecycle status of this workflow
   */
  status: "PUBLISHED" | "DRAFT" | "DELETED";
  /**
   * The name of this workflow
   */
  name: string;
  /**
   * The description of this workflow
   */
  description: string;
  /**
   * The components that make up this workflow
   */
  components: Array<ComponentDetails>;
  _links: {
    [key: string]: string;
  };
};

export type PageOfSessionSummary = {
  /**
   * The page of response data as an array
   */
  _embedded: Array<SessionSummary>;
  /**
   * The zero-indexed page number of the response data
   */
  _pageNumber: number;
  /**
   * True iff this page is the final page
   */
  _lastPage: boolean;
  _links: {
    [key: string]: string;
  };
};

/**
 * The page of response data as an array
 */
export type SessionSummary = {
  /**
   * The integer version of the workflow this session belongs to
   */
  workflowVersion: number;
  /**
   * UUID id of the session returned
   */
  sessionId: string;
  /**
   * The overall workflow status
   */
  status:
    | "IN_PROGRESS"
    | "SUCCESSFUL"
    | "WAITING"
    | "FAILED"
    | "TERMINATED"
    | "OUT_OF_QUOTA";
  startedAt?: string;
  updatedAt?: string;
  _links?: {
    [key: string]: string;
  };
};

/**
 * Flattened representation of the component result graph
 */
export type ComponentResult = {
  /**
   * UUID id of this Component Result
   */
  resultId: string;
  /**
   * UUID id of the Component this result is for
   */
  componentId: string;
  /**
   * The type of the Component this result is for
   */
  componentType: string;
  /**
   * The name of the Component this result is for
   */
  componentName: string;
  /**
   * The thread this Component was run in - either 'root' or a UUID id
   */
  thread: string;
  /**
   * The status of the execution of this Component
   */
  status:
    | "IN_PROGRESS"
    | "SUCCESSFUL"
    | "WAITING"
    | "FAILED"
    | "TERMINATED"
    | "OUT_OF_QUOTA";
  /**
   * The error message generated if status=FAILED
   */
  errorMessage: string;
  nodeInput: JsonNode;
  nodeOutput: JsonNode;
  /**
   * The resultIds of the following results in the result graph
   */
  nextResults: Array<string>;
  startedAt?: string;
  updatedAt?: string;
};

/**
 * The JSON result that was output from this execution
 */
export type JsonNode = {
  [key: string]: unknown;
};

/**
 * JSON representation of a Workflow Session
 */
export type SessionResult = {
  /**
   * The integer version of the workflow this session belongs to
   */
  workflowVersion: number;
  /**
   * UUID id of the session returned
   */
  sessionId: string;
  /**
   * The overall workflow status
   */
  status:
    | "IN_PROGRESS"
    | "SUCCESSFUL"
    | "WAITING"
    | "FAILED"
    | "TERMINATED"
    | "OUT_OF_QUOTA";
  startedAt?: string;
  updatedAt?: string;
  /**
   * The execution mode of this session
   */
  mode: "PROD" | "TEST";
  /**
   * Flattened representation of the component result graph
   */
  componentResults: Array<ComponentResult>;
  _links?: {
    [key: string]: string;
  };
};

export type RunWorkflowData = {
  body: RunWorkflowCommand;
  path: {
    workflowId: string;
  };
  query?: never;
  url: "/v1/workflow/{workflowId}/run";
};

export type RerunWorkflowData = {
  body: RerunWorkflowCommand;
  path: {
    workflowId: string;
  };
  query?: never;
  url: "/v1/workflow/{workflowId}/run";
};

export type RunWorkflowErrors = {
  /**
   * General validation errors
   */
  400: StandardWorkflow86Exception;
  /**
   * No API Key header provided
   */
  401: StandardWorkflow86Exception;
  /**
   * The provided API Key was invalid, or deleted
   */
  403: StandardWorkflow86Exception;
  /**
   * Entity not found, or deleted
   */
  410: StandardWorkflow86Exception;
  /**
   * All unexpected errors, and outages
   */
  500: StandardWorkflow86Exception;
};

export type RunWorkflowError = RunWorkflowErrors[keyof RunWorkflowErrors];

export type RunWorkflowResponses = {
  /**
   * OK
   */
  200: RunWorkflowResponse;
};

export type RunWorkflowResponse2 =
  RunWorkflowResponses[keyof RunWorkflowResponses];

export type ListWorkflowsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Optional parameter to filter results by publication status
     */
    status?: "ALL" | "PUBLISHED" | "DRAFT";
    pageNumber?: number;
  };
  url: "/v1/workflow";
};

export type ListWorkflowsErrors = {
  /**
   * General validation errors
   */
  400: StandardWorkflow86Exception;
  /**
   * No API Key header provided
   */
  401: StandardWorkflow86Exception;
  /**
   * The provided API Key was invalid, or deleted
   */
  403: StandardWorkflow86Exception;
  /**
   * Entity not found, or deleted
   */
  410: StandardWorkflow86Exception;
  /**
   * All unexpected errors, and outages
   */
  500: StandardWorkflow86Exception;
};

export type ListWorkflowsError = ListWorkflowsErrors[keyof ListWorkflowsErrors];

export type ListWorkflowsResponses = {
  /**
   * OK
   */
  200: PageOfWorkflowSummary;
};

export type ListWorkflowsResponse =
  ListWorkflowsResponses[keyof ListWorkflowsResponses];

export type GetWorkflowData = {
  body?: never;
  path: {
    workflowId: string;
  };
  query?: never;
  url: "/v1/workflow/{workflowId}";
};

export type GetWorkflowErrors = {
  /**
   * General validation errors
   */
  400: StandardWorkflow86Exception;
  /**
   * No API Key header provided
   */
  401: StandardWorkflow86Exception;
  /**
   * The provided API Key was invalid, or deleted
   */
  403: StandardWorkflow86Exception;
  /**
   * Entity not found, or deleted
   */
  410: StandardWorkflow86Exception;
  /**
   * All unexpected errors, and outages
   */
  500: StandardWorkflow86Exception;
};

export type GetWorkflowError = GetWorkflowErrors[keyof GetWorkflowErrors];

export type GetWorkflowResponses = {
  /**
   * OK
   */
  200: WorkflowVersionSummary;
};

export type GetWorkflowResponse =
  GetWorkflowResponses[keyof GetWorkflowResponses];

export type GetWorkflowVersionData = {
  body?: never;
  path: {
    workflowId: string;
    version: string;
  };
  query?: never;
  url: "/v1/workflow/{workflowId}/{version}";
};

export type GetWorkflowVersionErrors = {
  /**
   * General validation errors
   */
  400: StandardWorkflow86Exception;
  /**
   * No API Key header provided
   */
  401: StandardWorkflow86Exception;
  /**
   * The provided API Key was invalid, or deleted
   */
  403: StandardWorkflow86Exception;
  /**
   * Entity not found, or deleted
   */
  410: StandardWorkflow86Exception;
  /**
   * All unexpected errors, and outages
   */
  500: StandardWorkflow86Exception;
};

export type GetWorkflowVersionError =
  GetWorkflowVersionErrors[keyof GetWorkflowVersionErrors];

export type GetWorkflowVersionResponses = {
  /**
   * OK
   */
  200: WorkflowVersionSummary;
};

export type GetWorkflowVersionResponse =
  GetWorkflowVersionResponses[keyof GetWorkflowVersionResponses];

export type ListWorkflowSessionsData = {
  body?: never;
  path: {
    workflowId: string;
  };
  query?: {
    mode?: "PROD" | "TEST";
    pageNumber?: number;
  };
  url: "/v1/workflow/{workflowId}/sessions";
};

export type ListWorkflowSessionsErrors = {
  /**
   * General validation errors
   */
  400: StandardWorkflow86Exception;
  /**
   * No API Key header provided
   */
  401: StandardWorkflow86Exception;
  /**
   * The provided API Key was invalid, or deleted
   */
  403: StandardWorkflow86Exception;
  /**
   * Entity not found, or deleted
   */
  410: StandardWorkflow86Exception;
  /**
   * All unexpected errors, and outages
   */
  500: StandardWorkflow86Exception;
};

export type ListWorkflowSessionsError =
  ListWorkflowSessionsErrors[keyof ListWorkflowSessionsErrors];

export type ListWorkflowSessionsResponses = {
  /**
   * OK
   */
  200: PageOfSessionSummary;
};

export type ListWorkflowSessionsResponse =
  ListWorkflowSessionsResponses[keyof ListWorkflowSessionsResponses];

export type GetWorkflowSessionData = {
  body?: never;
  path: {
    sessionId: string;
  };
  query?: never;
  url: "/v1/session/{sessionId}";
};

export type GetWorkflowSessionErrors = {
  /**
   * General validation errors
   */
  400: StandardWorkflow86Exception;
  /**
   * No API Key header provided
   */
  401: StandardWorkflow86Exception;
  /**
   * The provided API Key was invalid, or deleted
   */
  403: StandardWorkflow86Exception;
  /**
   * Entity not found, or deleted
   */
  410: StandardWorkflow86Exception;
  /**
   * All unexpected errors, and outages
   */
  500: StandardWorkflow86Exception;
};

export type GetWorkflowSessionError =
  GetWorkflowSessionErrors[keyof GetWorkflowSessionErrors];

export type GetWorkflowSessionResponses = {
  /**
   * OK
   */
  200: SessionResult;
};

export type GetWorkflowSessionResponse =
  GetWorkflowSessionResponses[keyof GetWorkflowSessionResponses];

export type ClientOptions = {
  baseUrl: `${string}://rest.workflow86.com` | (string & {});
};
