name: Publish to npmjs

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
          scope: '@npm-workflow86'

      - name: Install dependencies
        run: npm install

      - name: Verify tag matches package.json version
        run: |
          TAG_VERSION="${GITHUB_REF##*/}"
          PKG_VERSION="v$(node -p "require('./package.json').version")"

          echo "Git tag: $TAG_VERSION"
          echo "package.json version: $PKG_VERSION"

          if [ "$TAG_VERSION" != "$PKG_VERSION" ]; then
            echo "❌ Tag does not match package.json version"
            exit 1
          fi

      - name: Check generated client
        run: |
          npm run genclient
          if [ -n "$(git status --porcelain)" ]; then
            echo "❌ Generated client not in sync with prod OpenAPI spec:"
            git status --porcelain
            git diff
            exit 1
          fi
          echo "✅ Generated client in sync with prod"

      - name: Build
        run: |
          npm run build
          npm run test

      - name: Publish to npmjs
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}