name: Publish to npmjs

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
          scope: '@npm-workflow86'

      - name: Install dependencies
        run: npm install

      - name: Verify tag matches package.json version
        run: |
          TAG_VERSION="${GITHUB_REF##*/}"
          PKG_VERSION="v$(node -p "require('./package.json').version")"

          echo "Git tag: $TAG_VERSION"
          echo "package.json version: $PKG_VERSION"

          if [ "$TAG_VERSION" != "$PKG_VERSION" ]; then
            echo "❌ Tag does not match package.json version"
            exit 1
          fi

      - name: Build
        run: npm run build

      - name: Publish to npmjs
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}