name: Build and Publish

on:
  push:
    branches:
      - '**' # Not Tags
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
          scope: '@npm-workflow86'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: |
          npm run build
          npm run test

      - name: Format Check
        run: npm run check

      - name: Publish Dry Run
        run: npm publish --dry-run

      - name: Publish canary
        if: github.ref == 'refs/heads/main'
        run: |
          BASE_VERSION=$(node -p "require('./package.json').version.split('-')[0]")
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          npm version "${BASE_VERSION}-canary.${SHORT_SHA}" --no-git-tag-version
          npm publish --tag canary --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  check-generated-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
          scope: '@npm-workflow86'

      - name: Install dependencies
        run: npm install

      - name: Check generated client
        run: |
          npm run genclient
          if [ -n "$(git status --porcelain)" ]; then
            echo "❌ Public API changes have not been deployed to prod yet (or you need to run genclient and commit)"
            git status --porcelain
            git diff
            exit 1
          fi
          echo "✅ Ready to Tag"

  publish:
    runs-on: ubuntu-latest
    needs: [build, check-generated-client]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
          scope: '@npm-workflow86'

      - name: Install dependencies
        run: npm install

      - name: Create version tag and publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          VERSION_TO_TAG=$CURRENT_VERSION

          # If current version already has a tag, bump patch version first
          if git tag -l | grep -q "^v${CURRENT_VERSION}$"; then
            echo "Version has not been bumped - Not publishing"
            exit 1
          fi

          # Build and publish first
          npm run build
          npm publish
          
          # Only create tag after successful publish
          git tag "v${VERSION_TO_TAG}"
          git push origin main --tags
